<h1>Report 1<h1/>

In this notebook I am going to present the code for the resolution of the Assessment 1 in the module "Programming and Policy Analysis".

<h2>Loading Database<h2/>

In this section I am going to upload the database. It could be any database, but in this case I will use the database "Student Performance" from an Introductory Paper for 5th Annual Future Business Technology Conference. I will import from an Excel file.

In [32]:
%pip install pandas openpyxl

import pandas as pd

RFM_df = pd.read_excel('C:/Users/FRowland/Desktop/JN/student-mat.xlsx')
RFM_df.head()

# Import some libraries for working in a better way

import pandas as pd
import numpy as np

# Matrix of dependent variable
dg=pd.DataFrame(RFM_df)
dependent=dg[['G3']].to_numpy()

print(dependent)

Note: you may need to restart the kernel to use updated packages.
[[ 6]
 [ 6]
 [10]
 [15]
 [10]
 [15]
 [11]
 [ 6]
 [19]
 [15]
 [ 9]
 [12]
 [14]
 [11]
 [16]
 [14]
 [14]
 [10]
 [ 5]
 [10]
 [15]
 [15]
 [16]
 [12]
 [ 8]
 [ 8]
 [11]
 [15]
 [11]
 [11]
 [12]
 [17]
 [16]
 [12]
 [15]
 [ 6]
 [18]
 [15]
 [11]
 [13]
 [11]
 [12]
 [18]
 [11]
 [ 9]
 [ 6]
 [11]
 [20]
 [14]
 [ 7]
 [13]
 [13]
 [10]
 [11]
 [13]
 [10]
 [15]
 [15]
 [ 9]
 [16]
 [11]
 [11]
 [ 9]
 [ 9]
 [10]
 [15]
 [12]
 [ 6]
 [ 8]
 [16]
 [15]
 [10]
 [ 5]
 [14]
 [11]
 [10]
 [10]
 [11]
 [10]
 [ 5]
 [12]
 [11]
 [ 6]
 [15]
 [10]
 [ 8]
 [ 6]
 [14]
 [10]
 [ 7]
 [ 8]
 [18]
 [ 6]
 [10]
 [14]
 [10]
 [15]
 [10]
 [14]
 [ 8]
 [ 5]
 [17]
 [14]
 [ 6]
 [18]
 [11]
 [ 8]
 [18]
 [13]
 [16]
 [19]
 [10]
 [13]
 [19]
 [ 9]
 [16]
 [14]
 [13]
 [ 8]
 [13]
 [15]
 [15]
 [13]
 [13]
 [ 8]
 [12]
 [11]
 [ 9]
 [ 0]
 [18]
 [ 0]
 [ 0]
 [12]
 [11]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [12]
 [15]
 [ 0]
 [ 9]
 [11]
 [13]
 [ 0]
 [11]
 [ 0]
 [11]
 [ 0]
 [10]
 [ 0]
 [14]
 [10]
 [ 0]
 [12]
 [ 8


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


395

<h2>Estimation of Parameters<h2/>

In this section I am going to estimate the parameters of the OLS. The first step is to create an unitary matrix.

In [33]:
matrix_one=[]

for f in range(len(dependent)):
    matrix_one.append([])
    for c in range(1):
        matrix_one[f].append(1)


print(matrix_one)

[[1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1],

Next, I am going to create a matrix of independent variables that will be united with the unitary matrix. Furthermore, it will be created the matrix of dependent variable.

In [34]:
# Matrix of independent variables
independent=dg[['age','traveltime','studytime','famrel','freetime','absences']].to_numpy()

# Unitary matrix is transformed in an array
matrix_one=np.array(matrix_one)

# Unitary matrix is united with independent variables
explicative=np.hstack((matrix_one,independent))

# Matrix of independent variables (united to unitary matrix) is transposed
x_t=np.transpose(explicative)

# Estimation of betas
betas=np.linalg.inv(x_t@explicative)@x_t@dependent
print(betas)

[[18.82485419]
 [-0.61262717]
 [-0.61382494]
 [ 0.50849645]
 [ 0.28221573]
 [ 0.09973841]
 [ 0.04149789]]


<h2>Standard Errors<h2/>

In this section it will be estimated the Standard Errors

In [35]:
# It is calculated the residuals 
residuos=dependent-explicative@betas

# It is calculated the variance of the errors
var_errors=(np.transpose(residuos)@residuos)*(1/(len(residuos)-explicative.shape[1]))

#It is calculated the Var-Cov matrix
var_cov=var_errors*np.linalg.inv(x_t@explicative)

#It is calculated the standard errors
standard_errors=np.sqrt(np.diag(var_cov))
print(standard_errors)

[3.22553758 0.18107076 0.32735376 0.27523638 0.25641404 0.23246929
 0.02889783]


<h2>t-Statistics<h2/>

In this section I am going to calculate the t statistics associated with each beta.

In [36]:
# The shape of standard errors is changed for allowing the calculation
standard_errors1=standard_errors.reshape(7,1)

# The t-statistics are calculated for each beta
t_statistics=betas*np.reciprocal(standard_errors1)

print(t_statistics)

[[ 5.83619125]
 [-3.38335791]
 [-1.87511191]
 [ 1.84748993]
 [ 1.10062512]
 [ 0.42903907]
 [ 1.43602123]]


<h2>p-Values<h2/>

In this section I am going to calculate the p values associated to each beta.

In [37]:
# Import this library for getting the cumulative distribution function
from scipy import stats

#p-values are estimated
p_value=2*(1-stats.t.cdf(abs(t_statistics),len(residuos)-explicative.shape[1]))
print(p_value)

[[1.12840290e-08]
 [7.88968943e-04]
 [6.15282106e-02]
 [6.54371908e-02]
 [2.71742199e-01]
 [6.68132908e-01]
 [1.51802030e-01]]


<h2>R-Square<h2/>

In this section I am going to calculate de R-Square of this regression.

In [38]:
# Average of the dependent variable
y_bar=np.sum(dependent)/len(dependent)

# Total Sum of Squares (SST)
SST=np.sum((dependent-y_bar)**2)

# Dependent variable estimated
y_hat=explicative@betas

# Residual Sum of Squares
SSE=np.sum((dependent-y_hat)**2)

# R-Square is calculated
R_square=1-(SSE/SST)
print(R_square)

0.0531948936191613
